### ISSUE TITLE
User password not correctly set from secret

### ISSUE THREAD

**Issue by mfedatto** [jc21/docker-mariadb-aria#11]
I've set up a secret for the user password on my `docker-compose.yml`, but it is not reflected on MySQL. Checked the content for `/run/secrets/mariadb_usr_pwd` both on the `mariadb` container and `app` container, and both matches my definition and each other. I tried to log-in to MySQL with that user and password from inside the `mariadb` container and got access denied. Where else may I check?

**Comment by jc21** [comment]
Are you able to replicate this same behaviour with the base image: [yobasystems/alpine-mariadb:10.4.15](https://hub.docker.com/r/yobasystems/alpine-mariadb) ?

**Comment by mfedatto** [comment]
It does

**Comment by jc21** [comment]
Then I'd suggest opening an issue with their repo: https://github.com/yobasystems/alpine-mariadb
