### ISSUE TITLE
Incorrect definition of table mysql.column_stats: expected 'hist_type' 'histogram'

### ISSUE THREAD

**Issue by HomelabHaven** [jc21/docker-mariadb-aria#13]
Hello there,

I am not sure if it has to do with the 262c780 commit but I've been seeing the following errors in the docker logs the past day:

> 2023-11-27 20:37:31 4 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
> 
> 2023-11-27 20:37:31 4 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).

Is this anything of note or can it be ignored?
The nginxproxymanager docker container that relies on the docker-mariadb-aria container is working normally as far as I can tell.

**Comment by jc21** [comment]
From [this](https://community.home-assistant.io/t/mariadb-errors-after-update/424731/2) search result, you might try these solutions:

```bash
docker exec -ti <name_of_your_docker_container> mysql_upgrade --user=root --password=<root_pwd>
```

or add this to your docker-compose environment section:

```yml
MARIADB_AUTO_UPGRADE: "1"
```

**Comment by HomelabHaven** [comment]
The first suggestions worked, thanks.
